name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Automatically deploy on push to main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'  # Use the appropriate Node version

      # Install dependencies
      - name: Install dependencies
        run: |
          npm install

      # Build the app and export it for static hosting
      - name: Build and Export
        run: |
          npm run build
          npm run export

      # Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./out  # The directory where Next.js exports the static files
          publish_branch: gh-pages  # Ensure the output is deployed to the gh-pages branch
